apiVersion: v1
kind: Service
metadata:
  name: polybot
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: yolo5
spec:
  selector:
    app: yolo5
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
