apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: background
spec:
  selector:
    app: background
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
